name: Playwright Tests

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - README.md
      - playwright.yml

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Install Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -zxvf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
        allure --version

    - name: Run Playwright Tests
      run: |
        pytest -v --alluredir=allure-results

    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Upload Playwright Traces
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-traces
        path: trace/
        retention-days: 7

    - name: Get Allure Report artifact ID
      id: get_artifact
      uses: actions/github-script@v6
      with:
        script: |
          const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          });
          const artifact = artifacts.data.artifacts.find(a => a.name === 'allure-report');
          if (!artifact) throw new Error('Artifact "allure-report" not found');
          return artifact.id;

    - name: Add Allure Report link to summary
      run: |
        echo "### ✅ [Download Allure Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.get_artifact.outputs.result }})" >> $GITHUB_STEP_SUMMARY
